### ISSUE TITLE
Component definition enhancements   

### ISSUE THREAD

**Issue by AlecTroemel** [AlecTroemel/junk-drawer#17]
Using this in an actual project has shown some missing pieces in the api. Specifically

### A way to designate and query singleton entities.
The main example being the "player" entity. Currently, we can create a `player` tag and query that in the system. But that will return a list, which is odd

```clojure
(def-tag player)
(def-system
  {players [:player]}
  (for plyr in players (pp plyr)))
```

One idea is to add an optional `singleton` arg to the `def-tag` function

```clojure
(def-tag player :singleton)
(def-system
  {plyr [:player]} # since player is singleton, is a single entity
  (pp plyr))
```

I'm still thinking through how this would interact with more complex entities & components

### Some stronger type enforcement on components
this is really a couple of things. I'd like to enforce the type of a components data, be able to provide the component keys when creating an entity, and be able to create components that just hold 1 thing. This possible api shows the changes Im thinking of

```clojure
# Just 1 data point in the component
(def-component name :string)

# provide the type of each key when component is a table
(def-component position
  :x :number
  :y :number)

# for table components, you provide the keys
(add-entity world
            (name "Bob Guy")
            (position :x 10 :y 10))
```

**Comment by pepe** [comment]
Ad singletons: what about destructuring in the query definition? Something like:

```
(def system 
  {[plyr] [:player]}
  (pp plyr))
```

It is from the top of my head, so probably wrong :-).

**Comment by AlecTroemel** [comment]
hmm destructuring is interesting.  You could then even do some more interesting  destructuring like this

```clojure
(def-system print-player-one-data
  {[[_ pos nm]] [:player :position :name]}
  (printf "player is named %s: at %q" nm pos))

(def-system two-players
  {[player-one player-two] [:player :position :name]}
  (pp player-one)
  (pp player-two))
``` 

there would be no enforcement that there would be only X players, but maybe that's not important (or even desirable)

**Comment by pepe** [comment]
Indeed, I was thinking this way too.

**Comment by AlecTroemel** [comment]
Oh wow so it turns out you can already do destructuring in the query section of the system. This works!

```clojure
(use /junk-drawer)

(def-component position x y)

(def-system print-test
  {[[pos]] [:position]}
  (pp pos))

(def world (create-world))
(add-entity world (position 10 10))
(register-system world print-test)
(:update world 1)

# prints "@{:x 10 :y 10}"
```

and in the new API 
```clojure
(use /junk-drawer)

(def-component position :x :number :y :number)

(def-system print-test
  {[[pos]] [:position]}
  (pp pos))

(def world (create-world))
(add-entity world (position :x 10 :y 10))
(register-system world print-test)
(:update world 1)

# prints "@{:x 10 :y 10}"
```

**Comment by AlecTroemel** [comment]
also, single value components (not wrapped in a table) ended up not being worth it, since those values are immutable in the system body
