### ISSUE TITLE
Rewrite Sparse set and cache in C

### ISSUE THREAD

**Issue by AlecTroemel** [AlecTroemel/junk-drawer#25]
from discussion here https://github.com/AlecTroemel/junk-drawer/issues/21#issuecomment-1206113247_

the idea is to make the spares set and cache abstract types in C. Should help increase performance even more!

**Comment by pepe** [comment]
I would love to help here. I have some experience extending Janet in C, mainly from https://git.sr.ht/~pepe/tahani :-).

**Comment by AlecTroemel** [comment]
@pepe if you were interested in tackling this that's more then ok to me! I was planning on focusing on docs + tests (along with some other game related janet bindings). So if this is something that sounds interesting or fun to you I wont get in your way!

**Comment by pepe** [comment]
Thank you. I will try then.

**Comment by pepe** [comment]
I have researched the current implementation and refreshed my knowledge about the Janet abstract types. 
There will be API changes, so we can utilize implicit properties of the Jat. For cache, implement the `put` and remove the `insert` method. Then the same for `get` and `_get`. Similar changes also apply to the sparse set.

**Comment by pepe** [comment]
Also, may I ask you to assign this issue to me so I see it in my issues?

**Comment by pepe** [comment]
One more thing. Would you mind if I attempt to use `jpm/cgen` for the C code?

**Comment by AlecTroemel** [comment]
@pepe my understand of `jpm/cgen` stops at the phrase "DSL for c bindings" :laughing:

I'm not apposed to that, plus reading your eventual PR would be a good way for me to learn more about it!

One question I do have, are there any performance differences between cgen and pure c bindings?

**Comment by pepe** [comment]
Thank you for your open-mindedness. There are no differences, as cgen is transpiled to C, which jpm compiles. 

My reasons are simple: I want to use it as much as possible, to get the feeling of the work with it. My current hope is that there will be good tooling (macros, static analysis) in the future. But eggs vs. chickens.

**Comment by pepe** [comment]
And if you are not sure you want `.cgen`s in your repo, we can take the product C code and continue with it. :-)

**Comment by pepe** [comment]
Anyway, you can check #27, where I started. If you deem it worthy, I will continue with the development.

**Comment by AlecTroemel** [comment]
closing for now, based on conversation in #27
